# Autogenerated by scripts/allocate_ip.py at 2025-02-25T16:45:18.885984
gui_home_pod_gui_home_mgmt0_ip = 192.168.249.4
nats_pod_nats_eth0_ip = 10.0.0.101
nats_pod_nats_mgmt0_ip = 192.168.249.2
ppi_asterix_pod_gui_asterix_eth0_ip = 10.1.5.3
ppi_asterix_pod_gui_asterix_mgmt0_ip = 192.168.249.3
radar_converter_asterix_pod_radar_converter_eth0_ip = 10.1.5.2
radar_converter_asterix_pod_radar_converter_nats0_ip = 10.0.0.102
ppi_navico_pod_opencpn_eth0_ip = 10.1.5.14
ppi_navico_pod_opencpn_mgmt0_ip = 192.168.249.8
radar_converter_navico_pod_radar_converter_eth0_ip = 10.1.5.13
radar_converter_navico_pod_radar_converter_nats0_ip = 10.0.0.102
