# Autogenerated by scripts/allocate_ip.py at 2025-02-25T16:45:18.885984
nats_pod_nats_eth0_ip = 10.0.0.101
nats_pod_nats_mgmt0_ip = 192.168.249.2
ppi_asterix_pod_gui_asterix_eth0_ip = 192.168.1.12
ppi_asterix_pod_gui_asterix_mgmt0_ip = 192.168.249.7
radar_converter_asterix_pod_radar_converter_eth0_ip = 192.168.1..2
radar_converter_asterix_pod_radar_converter_nats0_ip = 10.0.0.102
ppi_navico_pod_opencpn_eth0_ip = 192.168.1.14
ppi_navico_pod_opencpn_mgmt0_ip = 192.168.249.8
radar_converter_navico_pod_radar_converter_eth0_ip = 192.168.1.13
radar_converter_navico_pod_radar_converter_nats0_ip = 10.0.0.103
