# Autogenerated by scripts/allocate_ip.py at 2025-02-25T14:26:38.675119
nats_pod_nats_eth0_ip = 10.0.0.101
nats_pod_nats_mgmt0_ip = 192.168.249.2
gui_home_pod_gui_home_mgmt0_ip = 192.168.249.9
gui_instruments_pod_gui_instruments_mgmt0_ip = 192.168.249.5