NETWORK_NAMES += NATS
NETWORK_NAMES += MANAGEMENT

NATS_NET_NAME = macyste_nats
NATS_NET_CIDR = 192.168.1.0/24
NATS_NET_DRIVER = macvlan

MANAGEMENT_NET_NAME = macyste_management
MANAGEMENT_NET_CIDR = 192.168.249.0/24
MANAGEMENT_NET_DRIVER = bridge
MANAGEMENT_NET_INTERNAL = true
